language: c

install:
 - sudo apt-get install mono-gmcs cli-common-dev > /dev/null
 - git clone https://github.com/marioclone/MarioData
 - cp -r MarioData/* .

script:
 - xbuild /p:Configuration=Release
 
